<?php

namespace ShopBundle\Repository;

/**
 * ProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSectionProducts($sectionCode){
        $q = $this->createQueryBuilder('p')
            ->select('p.id', 'p.code', 'p.name', 'p.price', 'p.picture')
            ->orderBy('p.id', 'DESC');

        $q->leftJoin('p.section', 's');
        if ($sectionCode) {
            $q->where('s.code = (:code)')
                ->setParameter('code', $sectionCode);
        }
        return $q->getQuery()
            ->getResult();
    }
}
